server:
  port: 3000

app:
  # In Java ZoneOffset notation (https://docs.oracle.com/javase/8/docs/api/java/time/ZoneOffset.html#of-java.lang.String-)
  # 'Z' is code for UTC
  timezone: Z

api:
  # Should an authorization token be required?
  requireAuthorization: true
  # Auth token (must be included in calls to this app if enabled)
  authToken: basic e35acfe4e0b54d488b687a64914197ad
  # Should calls to /kv/get-all include lastModifiedTimestamps? (more resource intensive)
  includeTimestampsInGetAll: true

db:
  # Frequency to store data to db (in minutes)
  storeInterval: 5
  # Run all insert statements at once? True means only one SQL statement needs to be run, but if it fails then all values
  # will fail to insert. False means many SQL statements need to be run but if any errors only that one will fail.
  insertAllAtOnce: true